on:
  push:
    branches:
      - master

env:
  BUILD_TAG: ${{ env:GITHUB_REF_NAME }}-${{ env:GITHUB_RUN_NUMBER }}

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: master
          path: code

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

      - name: Build container image
        run: |
          cd $GITHUB_WORKSPACE/code
          docker build -t ${{ vars.DOCKER_REPO }}:$BUILD_TAG .

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push image to Docker Hub
        run: docker push ${{ vars.DOCKER_REPO }}:$BUILD_TAG

      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: paulovigne/pipeline-hellogo-infra
          ref: master
          token: ${{ secrets.INFRA_GITREPO_TOKEN }}
          path: infra

      - name: Update k8s manifests
        uses: mikefarah/yq@master
        with:
          cmd: |
            export K8S_NAMESPACE=${{ vars.K8S_NAMESPACE }}
            export APPNAME=${{ vars.APPNAME }}
            export IMAGE=${{ vars.DOCKER_REPO }}:$BUILD_TAG
            export K8S_INGRESS_HOST=${{ vars.K8S_INGRESS_HOST }}

            yq -i '
              .metadata.name = strenv(APPNAME) |
              .metadata.namespace = strenv(K8S_NAMESPACE) |
              .metadata.labels.app = strenv(APPNAME) |
              .spec.selector.matchLabels.app = strenv(APPNAME) |
              .spec.template.metadata.labels.app = strenv(APPNAME) |
              .spec.template.spec.containers[0].name = strenv(APPNAME) |
              .spec.template.spec.containers[0].image = strenv(IMAGE)
            ' $GITHUB_WORKSPACE/infra/k8s/deployment.yaml

            yq -i '
              .metadata.name = strenv(APPNAME) |
              .metadata.namespace = strenv(K8S_NAMESPACE) |
              .spec.selector.app = strenv(APPNAME)
            ' $GITHUB_WORKSPACE/infra/k8s/service.yaml

            yq -i '
              .metadata.name = strenv(APPNAME) |
              .metadata.namespace = strenv(K8S_NAMESPACE) |
              .spec.rules[0].host = strenv(K8S_INGRESS_HOST) |
              .spec.rules[0].http.paths[0].backend.service.name = strenv(APPNAME)
            ' $GITHUB_WORKSPACE/infra/k8s/ingress.yaml            

      - name: checkin infra repo
        run: |
          COMMIT=$(echo Modified by Code Pipeline - `date`)
          cd $GITHUB_WORKSPACE/infra
          git config --global user.name ${{ vars.INFRA_GITREPO_USERNAME }}
          git config --global user.password ${{ secrets.INFRA_GITREPO_TOKEN }}
          git config --global user.email "you@example.com"
          git add .
          git commit -m "$COMMIT"
          git push
